name: Lint files

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.5
        with:
          prettier_version: '3.2.5'
          dry: True
          prettier_options: --check **/*.{ts,tsx,js,md,html,json} #todo add svg
