name: Teardown preview

on:
  pull_request:
    types:
      - closed

env:
  tag: preview-${{ github.event.number }}

jobs:
  teardown:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Stop the containers with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd previews/${{ env.tag }}

            TAG=${{ env.tag }} \
              DB_USERNAME=dundring \
              DB_PASSWORD=password \
              CLOUDFLARE_DNS_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} \
              MAIL_HOST=${{ secrets.MAIL_HOST }} \
              MAIL_PORT=${{ secrets.MAIL_PORT }} \
              MAIL_USER=${{ secrets.MAIL_USER }} \
              MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}' \
              STRAVA_CLIENT_ID='${{ secrets.STRAVA_CLIENT_ID }}' \
              STRAVA_CLIENT_SECRET='${{ secrets.STRAVA_CLIENT_SECRET }}' \
              docker-compose down
